from django.conf.urls import url, include
from rest_framework import routers
from mongoapp.views import ToolViewSet, BookViewSet, AuthorViewSet

router = routers.DefaultRouter()
#router.register(r'tools', ToolViewSet)
#router.register(r'books', BookViewSet)
router.register(r'authors', AuthorViewSet,r"author")
#router.register(r'authors', AuthorViewSet)
# register REST API endpoints with DRF router
router.register(r'tool', ToolViewSet, r"tool")

urlpatterns = [
    
    # REST API root view (generated by DRF router)
    url(r'^service/', include(router.urls)),
    
]
